### ISSUE TITLE
How to get data in other langauges (e.g., Chinese or Japanese)?

### ISSUE THREAD

**Issue by gamer-mitsuha** [reko-beep/hsr-data#1]
Thanks for the great work! I'm wondering where to modify the code to fetch the data in other languages.

Could you give me some pointers? Thanks!

**Comment by reko-beep** [comment]
Ah sorry, the script in main branch have stopped working from last 5 days. Because the site structure changed that doesnot allow for scraping from js chunk files anymore.

You can use ```raw_data.py``` from dev branch.
It is a bit documented. 

It is still work in progress because I have not typed the models yet. Nonetheless, it will fetch all data and save it in json, as far as I have tried.

the ```O_VALUE``` in ```constants.py``` sometimes changes. Its working for now, so you would have to look in site main js file.
You can dm me on discord if you need any help. ```reko#8221```

**Comment by gamer-mitsuha** [comment]
Thanks for the quick response! And really appreciate the comprehensive explanation.

I'll give the dev branch a try. And I'm glad to connect through discord : ) (I'm making discord bots for HSR.)
